name: Publish Docker image to GitHub Package Registry and Docker Hub

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@master

    - name: Publish Docker Image to GPR
      uses: elgohr/Publish-Docker-Github-Action@master
      id: docker
      with:
        name: mmedum/docker-mkdocs
        username: ${{ secrets.GIT_DOCKER_USER }}
        password: ${{ secrets.GIT_DOCKER_PASS }}
        registry: docker.pkg.github.com
